# Application Name
spring.application.name=Antigravity Supply Chain

# Server Port
server.port=8080

# Google Auth
google.client.id=399311351842-m2d1ga59mlh7imaadjee3eio0p34trb2.apps.googleusercontent.com

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sugavaneshwaran27@gmail.com
spring.mail.password=clmc ubob txyb teyy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/supply_chain_db
spring.datasource.username=postgres
spring.datasource.password=suga@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Key
jwt.secret=blockchain-supply-chain-secret-key-2025-sih45-secure
jwt.expiration=86400000

# Blockchain Settings (Sepolia Testnet)
blockchain.network=sepolia
blockchain.rpc.url=https://sepolia.infura.io/v3/e64e0bd397124903b6f9317643c40c12
blockchain.contract.address=0x41e355475f37ff1dc9b2764a7e0ee16f2f73bf1b
blockchain.wallet.private-key=f598272adf184e6c0da33fcdebe79f8825ccc0718efa902e838487fd058e030a
web3j.client-address=${blockchain.rpc.url}
blockchain.gas.price=20000000000
blockchain.gas.limit=6721975
