# Application Name
spring.application.name=blockchain-supply-chain

# Server Port
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/supply_chain_db
spring.datasource.username=postgres
spring.datasource.password=suga@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Key
jwt.secret=blockchain-supply-chain-secret-key-2025-sih45-secure
jwt.expiration=86400000
